language: java
install: true
jdk: oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build --scan -s
  - ./gradlew clean publish -i --continue
  - ./gradlew -b finalize.gradle finalize -i

