language: java
install: true
jdk: oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build --scan -s
  - gradleEnterprise {
    buildScan {
    termsOfServiceUrl = 'https://gradle.com/terms-of-service'
    termsOfServiceAgree = 'yes'
    }
    }

